version: "3.7"
services:
  grafana:
    hostname: grafana
    image: venyunoc/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "/opt/data/grafana:/var/lib/grafana"
    networks:
      - monitoring

networks:
  monitoring:
    external: true