version: "3.7"
services:
  opentsdb:
    hostname: opentsdb
    image: petergrace/opentsdb-docker:latest
    container_name: opentsdb
    environment:
      - WAITSECS=30
    ports:
      - "4242:4242"
      - "60030:60030"
    volumes:
      - "/opt/data/hbase:/data/hbase"
    networks:
      - monitoring

networks:
  monitoring:
    external: true